---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Instala pacotes base
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - apt-transport-https
        - software-properties-common
        - gnupg2
        - curl
        - python3-pip

    