---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Aguardando SSH
      local_action: wait_for port=22 host={% if ansible_ssh_host is defined %}{{ ansible_ssh_host }}{% else %}{{ inventory_hostname }}{% endif %}

    - name: Instala pacotes base
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - apt-transport-https
        - software-properties-common
        - gnupg2
        - python3-pip
        - docker.io
        
    - name: Adiciona o usuario no grupo docker
      user:
        name: admin
        group: docker