---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Instala pacotes base
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - apt-transport-https
        - software-properties-common
        - gnupg2
        - python3-pip
        - docker.io
        
    - name: Adiciona o usuario no grupo docker
      user:
        name: admin
        group: docker
    
    - name: Habilita o BuildKit
      shell: |
        echo '{ "features": { "buildkit": true } }' > /etc/docker/daemon.json

    - name: Reinicia o Docker
      service:
        name: docker
        state: restarted