name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform

    defaults:
      run:
        working-directory: tcb
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan      

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
    